version: '3'

services:
  app:
    build: .
    ports:
      - "50051:50051"
    environment:
      - SERVER_PORT=50051
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DATABASE=github_parser
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      - mongo
    restart: on-failure

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: